[package]
name = "gen-proxy-ffi"
version = "0.1.0"
authors = ["Tong Zhigao <tongzhigao@pingcap.com>"]
edition = "2018"

[[bin]]
name = "gen-proxy-ffi"

[dependencies.bindgen]
version = ""
default-features = false
features = ["which-rustfmt"]

[dependencies]
walkdir = "2"
md5 = ""
clap = ""
