[package]
name = "engine_test"
version = "0.0.1"
description = "A single engine that masquerades as all other engines, for testing"
edition = "2018"
publish = false

[features]
default = ["test-engine-kv-rocksdb", "test-engine-raft-raft-engine"]

test-engine-kv-panic = []
test-engine-kv-rocksdb = []
test-engine-raft-panic = []
test-engine-raft-rocksdb = []
test-engine-raft-raft-engine = []

test-engines-rocksdb = [
  "test-engine-kv-rocksdb",
  "test-engine-raft-rocksdb",
]
test-engines-panic = [
  "test-engine-kv-panic",
  "test-engine-raft-panic",
]

[dependencies]
encryption = { path = "../encryption", default-features = false }
engine_panic = { path = "../engine_panic", default-features = false }
engine_rocks = { path = "../engine_rocks", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
file_system = { path = "../file_system", default-features = false }
raft_log_engine = { path = "../raft_log_engine", default-features = false }
tempfile = "3.0"
tikv_alloc = { path = "../tikv_alloc" }
# FIXME: Remove this dep from the engine_traits interface
tikv_util = { path = "../tikv_util", default-features = false }
