[package]
name = "storage_types"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
quick-error = "1.2.2"

keys = { path = "../keys" }
tikv_util = { path = "../tikv_util" }
