[package]
name = "tikv_alloc"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]
publish = false

[features]
jemalloc = ["tikv-jemallocator", "tikv-jemalloc-ctl", "tikv-jemalloc-sys"]

# Build jemalloc's profiling features. Without this
# certain profile functions will return nothing.
mem-profiling = ["tikv-jemallocator/profiling", "log"]
mimalloc = ["mimallocator"]

[dependencies]
libc = "0.2"
log = { version = "0.4", optional = true }

[dev-dependencies]
tempfile = "3.0"

[dependencies.tikv-jemallocator]
version = "0.4.0"
optional = true
features = ["unprefixed_malloc_on_supported_platforms", "stats"]

[dependencies.tikv-jemalloc-sys]
version = "0.4.0"
optional = true
features = ["stats"]

[dependencies.tikv-jemalloc-ctl]
version = "0.4.0"
optional = true

[dependencies.tcmalloc]
version = "0.3.0"
optional = true
features = ["bundled"]

[dependencies.mimallocator]
version = "0.1.3"
optional = true
