sudo: false
language: rust
cache:
  directories:
  - $HOME/.cache/rocksdb
  - $HOME/.cache/kcov

matrix:
  include:
    - os: linux
      rust: nightly
      compiler: clang
      env: COMPILER=clang++-3.6
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
            packages: ['clang-3.6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'libjemalloc-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']
    - os: osx
      rust: nightly

install:
  - export KCOV_DIR=$HOME/.cache/kcov
  - export ROCKSDB_DIR=$HOME/.cache/rocksdb
  - make -f travis-build/Makefile prepare_${TRAVIS_OS_NAME}

script:
  - make -f travis-build/Makefile test_${TRAVIS_OS_NAME}
  - make -f travis-build/Makefile cover_${TRAVIS_OS_NAME}
