sudo: false
language: rust
cache:
  directories:
  - $HOME/.cache/
  - $HOME/.cargo/

matrix:
  include:
    - os: linux
      rust: nightly
      env: COMPILER=g++-4.8 RUSTC_DATE=2016-10-06
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-4.8', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']
    - os: linux
      rust: nightly
      env: COMPILER=g++-4.8 RUSTC_DATE=2016-08-06 ENABLE_FEATURES=default SKIP_TESTS=true
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-4.8', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']
    - os: osx
      rust: nightly
      env: COMPILER=clang++ RUSTC_DATE=2016-10-06

install:
  - export LOCAL_DIR=$HOME/.cache/
  - export PATH=$PATH:$LOCAL_DIR/bin:$HOME/.cargo/bin
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$LOCAL_DIR/lib
  - export LIBRARY_PATH=${LIBRARY_PATH}:$LOCAL_DIR/lib
  - export DYLD_LIBRARY_PATH=${DY_LIBRARY_PATH}:$LOCAL_DIR/lib
  - make -f travis-build/Makefile prepare_${TRAVIS_OS_NAME}

script:
  - make -f travis-build/Makefile test_${TRAVIS_OS_NAME}

after_success:
  # TODO add following into build progress after failed cases are resolved.
  - make -f travis-build/Makefile cover_${TRAVIS_OS_NAME}
