language: rust

rust:
  - nightly

os:
  - linux
  - osx

script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc-4.8 g++-4.8 zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - sudo apt-get install libgflags-dev
  - sudo apt-get install libsnappy-dev 
  - sudo apt-get install zlib1g-dev 
  - sudo apt-get install libbz2-dev
  - mkdir -p $TRAVIS_BUILD_DIR/extern/rocksdb
  - cd $TRAVIS_BUILD_DIR/extern && git clone git@github.com:facebook/rocksdb.git && cd rocksdb && make shared_lib
  - sudo cp -rf $TRAVIS_BUILD_DIR/extern/rocksdb/include/rocksdb /usr/local/include 
  - sudo cp -f $TRAVIS_BUILD_DIR/extern/rocksdb/librocksdb.so /usr/local/lib 
  - export LD_LIBRARY_PATH=/usr/local/lib

  - make
