[package]
name = "engine_rocks_helper"
version = "0.1.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]

[dependencies]
pd_client = { path = "../pd_client", default-features = false }
keys = { path = "../keys", default-features = false }
tikv_util = { path = "../tikv_util", default-features = false }
engine_rocks = { path = "../engine_rocks", default-features = false }
raftstore = { path = "../raftstore", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
protobuf = "2.8"
futures = "0.3"
tempfile = "3.0"
fail = "0.5"

[dev-dependencies]
engine_test = { path = "../engine_test" }