[package]
name = "cop_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "TiKV Coprocessor data types"

[dependencies]
tipb = { version = "0.0.1", git = "https://github.com/pingcap/tipb.git", rev = "af5d98495e746cc38f83b23be2ea4b3e4b2c437f" }
bitflags = "1.0"
enum-primitive-derive = "0.1"
num-traits = "0.2"
failure = "0.1"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
