[package]
name = "txn_types"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
byteorder = "1.2"
farmhash = "1.1.5"
<<<<<<< HEAD
hex = "0.4"
derive-new = "0.5"
=======
>>>>>>> 3b2c5337c... security: add log redaction check (#9250)
error_code = { path = "../error_code" }
codec = { path = "../codec" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-4.0", default-features = false }
slog = "2.3"
quick-error = "1.2.2"
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
<<<<<<< HEAD
=======
collections = { path = "../collections" }
log_wrappers = { path = "../log_wrappers" }
>>>>>>> 3b2c5337c... security: add log redaction check (#9250)
