[package]
name = "tidb_query_aggr"
version = "0.0.1"
edition = "2018"
publish = false
description = "Vector aggr functions of query engine to run TiDB pushed down executors"

[dependencies]
match_template = { path = "../match_template" }
tidb_query_codegen = { path = "../tidb_query_codegen" }
tidb_query_common = { path = "../tidb_query_common", default-features = false }
tidb_query_datatype = { path = "../tidb_query_datatype", default-features = false }
tidb_query_expr = { path = "../tidb_query_expr", default-features = false }
tikv_util = { path = "../tikv_util", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
tipb_helper = { path = "../tipb_helper", default-features = false }
