[package]
name = "log_wrappers"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
hex = "0.3"
kvproto = { git = "https://github.com/MyonKeminta/kvproto.git", default-features = false, branch = "misono/green-gc" }
slog = "2.3"
slog-term = "2.4"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
