[package]
name = "tidb_query_vec_expr"
version = "0.0.1"
edition = "2018"
publish = false
description = "Vector expressions of query engine to run TiDB pushed down executors"

[dependencies]
byteorder = "1.2"
codec = { path = "../codec" }
derive_more = "0.15.0"
hex = "0.3"
match_template = { path = "../match_template" }
num = { version = "0.2", default-features = false }
num-traits = "0.2"
openssl = { version = "0.10" }
protobuf = "2"
tidb_query_codegen = { path = "../tidb_query_codegen" }
tidb_query_datatype = { path = "../tidb_query_datatype" }
tidb_query_common = { path = "../tidb_query_common" }
tidb_query_shared_expr = { path = "../tidb_query_shared_expr" }
tikv_util = { path = "../tikv_util" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
twoway = "0.2.0"
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.prometheus-static-metric]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "fd122caa03de8e7e5e4fae9372583aebf19e39f6"

[dev-dependencies]
bstr = "0.2.8"
chrono = "0.4"
profiler = { path = "../profiler" }
panic_hook = { path = "../panic_hook" }
tipb_helper = { path = "../tipb_helper" }
