[package]
name = "cloud"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
    "kvproto/protobuf-codec",
    "tikv_util/protobuf-codec",
]
prost-codec = [
    "kvproto/prost-codec",
    "tikv_util/prost-codec",
]

[dependencies]
async-trait = "0.1"
derive_more = "0.99.3"
error_code = { path = "../error_code", default-features = false }
futures-io = "0.3"
kvproto = { rev = "f42e582bf0bb6bc2aee647e5f4126d51ccf6d377", git = "https://github.com/pingcap/kvproto.git", default-features = false }
openssl = "0.10"
protobuf = "2.8"
rusoto_core = "0.45.0"
thiserror = "1.0"
tikv_util = { path = "../tikv_util", default-features = false }
url = "2.0"

[dev-dependencies]
fail = "0.4"
