[package]
name = "cloud"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
    "kvproto/protobuf-codec",
]
prost-codec = [
    "kvproto/prost-codec",
]

[dependencies]
async-trait = "0.1"
derive_more = "0.99.3"
error_code = { path = "../error_code", default-features = false }
failure = "0.1"
futures-io = "0.3"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
openssl = "0.10"
protobuf = "2.8"
rusoto_core = "0.45.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_util = { path = "../tikv_util", default-features = false }
url = "2.0"
