[package]
name = "external_storage_export"
version = "0.0.1"
edition = "2018"
publish = false

[[bin]]
name = "tikv-cloud-storage"
required-features = ["cloud-storage-grpc"]

[lib]
name = "external_storage_export"
# Experimental feature to load the cloud storage code dynamically
# crate-type = ["lib", "cdylib"]

[features]
default = ["protobuf-codec", "cloud-gcp", "cloud-aws"]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "external_storage/protobuf-codec",
  "aws/protobuf-codec",
  "cloud/protobuf-codec",
  "gcp/protobuf-codec",
  "grpcio/protobuf-codec",
  "encryption/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "external_storage/prost-codec",
  "aws/prost-codec",
  "cloud/prost-codec",
  "gcp/prost-codec",
  "grpcio/prost-codec",
  "encryption/prost-codec",
]
cloud-aws = ["aws"]
cloud-gcp = ["gcp"]
cloud-storage-dylib = [
  "external_storage/cloud-storage-dylib",
  "ffi-support",
  "file_system",
  "futures",
  "libloading",
  "lazy_static",
  "once_cell",
  "protobuf",
  "slog",
  "slog-global",
  "tokio",
  "tokio-util",
]
cloud-storage-grpc = [
  "external_storage/cloud-storage-grpc",
  "grpcio",
  "file_system",
  "futures",
  "futures-executor",
  "libc",
  "signal",
  "slog",
  "slog-global",
  "slog-term",
  "tokio",
  "tokio-util",
  "nix",
]

[dependencies]
anyhow = "1.0"
aws = { optional = true, path = "../../cloud/aws", default-features = false }
cloud = { path = "../../cloud", default_features = false }
lazy_static = { optional = true, version = "1.3" }
gcp = { optional = true, path = "../../cloud/gcp", default-features = false }
grpcio = { optional = true, version = "0.9",  default-features = false, features = ["openssl-vendored"] }
encryption = { path = "../../encryption", default-features = false }
external_storage = { path = "../", default-features = false }
ffi-support = { optional = true, version = "0.4.2" }
file_system = { optional = true, path = "../../file_system" }
futures = { optional = true, version = "0.3" }
futures-executor = { optional = true, version = "0.3" }
futures-io = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["io"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-5.1", default-features = false }
libloading = { optional = true, version = "0.7.0" }
once_cell = { optional = true, version = "1.3.1" }
protobuf = { optional = true, version = "2" }
slog-global = { optional = true, version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_util = { path = "../../tikv_util" }
tokio = { optional = true, version = "0.2", features = ["time", "rt-core", "uds"] }
tokio-util = { optional = true, version = "0.3.1", features = ["compat"] }
url = "2.0"

[dev-dependencies]
matches = "0.1.8"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
rust-ini = "0.14.0"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "0.2.24", features = ["time"] }

[[example]]
name = "scli"

[target.'cfg(unix)'.dependencies]
nix = { optional = true, version = "0.11" }
signal = { optional = true, version = "0.6" }
libc = { optional = true, version = "0.2" }
slog = { optional = true, version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = { optional = true, version = "2.4" }
