[package]
name = "external_storage_export"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec", "cloud-gcp", "cloud-aws"]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "external_storage/protobuf-codec",
  "gcp/protobuf-codec",
  "aws/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "external_storage/prost-codec",
  "gcp/prost-codec",
  "aws/prost-codec",
]
cloud-aws = ["aws"]
cloud-gcp = ["gcp"]

[dependencies]
libloading = { version = "0.5.2", optional = true }
aws = { optional = true, path = "../../cloud/aws", default-features = false }
gcp = { optional = true, path = "../../cloud/gcp", default-features = false }
external_storage = { path = "../", default-features = false }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
url = "2.0"

[dev-dependencies]
structopt = "0.3"
tempfile = "3.1"
rust-ini = "0.14.0"
matches = "0.1.8"
