[package]
name = "engine"
version = "0.0.1"
edition = "2018"
publish = false

[features]
portable = ["engine_rocksdb/portable"]
sse = ["engine_rocksdb/sse"]

[dependencies]
kvproto = { git = "https://github.com/youjiali1995/kvproto.git", branch="pessimistic-dev" }
protobuf = "~2.0"
raft = "0.4"
quick-error = "1.2.2"
crc = "1.8"
lazy_static = "0.2.1"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
time = "0.1"
sys-info = "0.5.1"
tikv_alloc = { path = "../tikv_alloc", default-features = false }

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly"]

[dependencies.engine_rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
tempdir = "0.3"
