[package]
name = "engine"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["engine_rocksdb/jemalloc"]
portable = ["engine_rocksdb/portable"]
sse = ["engine_rocksdb/sse"]

[dependencies]
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-3.1" }
protobuf = "~2.0"
raft = "0.4"
quick-error = "1.2.2"
lazy_static = "1.4"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
time = "0.1"
sys-info = "0.5.7"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
hex = "0.3"
tikv_util = { path = "../tikv_util" }

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly"]

[dependencies.engine_rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"
branch = "tikv-3.x"

[dev-dependencies]
tempdir = "0.3"
