[package]
name = "fuzz"
version = "0.0.1"
publish = false

[[bin]]
name = "fuzz"
path = "cli.rs"

[dependencies]
cargo_metadata = "0.6"
clap = "2.32.0"
structopt = "0.2"
failure = "0.1"
lazy_static = "1.3"
regex = "1.1"
