[package]
name = "import"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
lazy_static = "1.3"
quick-error = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.6", features = [ "serde", "v4" ] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
engine = { path = "../engine" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }

[dependencies.prometheus]
version = "0.4.2"
default-features = false

[dev-dependencies]
tempfile = "3.0"
