[package]
name = "tidb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "TiKV query engine data types"

[features]
protobuf-codec = ["tipb/protobuf-codec"]
prost-codec = ["tipb/prost-codec"]

[dependencies]
bitflags = "1.0"
error_code = { path = "../error_code" }
failure = "0.1"
tikv_alloc = { path = "../tikv_alloc" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
