[package]
name = "tidb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "Data type of a query engine to run TiDB pushed down executors"

[features]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "tipb/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "tipb/prost-codec",
]

[dependencies]
bitfield = "0.13.2"
bitflags = "1.0.1"
boolinator = "2.4.0"
chrono = "0.4"
chrono-tz = "0.5.1"
codec = { path = "../codec" }
error_code = { path = "../error_code" }
failure = "0.1"
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
match_template = { path = "../match_template" }
nom = { version = "5.1.0", default-features = false, features = ["std"] }
num = { version = "0.3", default-features = false }
num-traits = "0.2"
num-derive = "0.3"
ordered-float = "1.0"
protobuf = "2"
quick-error = "1.2.3"
regex = "1.1"
serde = "1.0"
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_util = { path = "../tikv_util" }
collections = { path = "../collections" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
static_assertions = { version = "1.0", features = ["nightly"] }
tidb_query_common = { path = "../tidb_query_common" }
tikv_alloc = { path = "../tikv_alloc" }
bstr = "0.2.8"
