[package]
name = "tidb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "Data type of a query engine to run TiDB pushed down executors"

[dependencies]
bitfield = "0.13.2"
bitflags = "1.0.1"
boolinator = "2.4.0"
bstr = "0.2.8"
chrono = "0.4"
chrono-tz = "0.5.1"
codec = { path = "../codec", default-features = false }
collections = { path = "../collections" }
encoding_rs = { git = "https://github.com/xiongjiwei/encoding_rs.git", rev = "68e0bc5a72a37a78228d80cd98047326559cf43c" }
error_code = { path = "../error_code", default-features = false }
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
lazy_static = "1.3"
log_wrappers = { path = "../log_wrappers" }
match_template = { path = "../match_template" }
nom = { version = "5.1.0", default-features = false, features = ["std"] }
num = { version = "0.3", default-features = false }
num-derive = "0.3"
num-traits = "0.2"
ordered-float = "1.0"
protobuf = "2"
regex = "1.1"
serde = "1.0"
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
static_assertions = { version = "1.0", features = ["nightly"] }
thiserror = "1.0"
tidb_query_common = { path = "../tidb_query_common", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git" }
