[package]
name = "azure"
version = "0.0.1"
edition = "2021"
publish = false

[features]
failpoints = ["fail/failpoints"]

[dependencies]
async-trait = "0.1"
azure_core = { version = "0.12.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_identity = { version = "0.12.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_security_keyvault = { version = "0.12.0", git = "https://github.com/Azure/azure-sdk-for-rust", default-features = false }
azure_storage = { version = "0.12.0", git = "https://github.com/Azure/azure-sdk-for-rust", default-features = false }
azure_storage_blobs = { version = "0.12.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
base64 = "0.13"
cloud = { workspace = true }
fail = "0.5"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
kvproto = { workspace = true }
oauth2 = { version = "4.0.0", default-features = false }
openssl = { version = "0.10.50" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { workspace = true }
slog-global = { workspace = true }
tikv_util = { workspace = true }
time = { version = "0.3", features = ["local-offset"] }
tokio = { version = "1.5", features = ["time"] }
url = "2.0"
uuid = { version = "1.0", features = ["v4"] }
