[package]
name = "req_cpu"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3"
collections = { path = "../collections" }
libc = "0.2"
crossbeam = "0.8"
pin-project = "1.0"
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false, rev="511a3225c29f9272af83d28efed92eba835cd34f" }

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "5125fc1a69496b73b26b3c08b6e8afc3c665a56e" }

[dev-dependencies]
rand = "0.8"
