[package]
name = "engine_tiflash"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
failpoints = ["fail/failpoints"]
testexport = ["engine_traits/testexport", "engine_panic/testexport", "engine_rocks/testexport"]

# Disables runtime checks of invariants required by RocksDB that are redundant
# with assertions inside RocksDB itself. This makes it possible to test those
# invariants in Rust tests, resulting an a panic instead of an abort, at the
# expense of an extra branch. This feature exists to mark those extra branches.
# The checks _can_ be disabled by enabling this feature, though it may not
# result in any real performance improvement to do so, and it will break
# the test suite.
#
# Probably these checks should be in the rust-rocksdb crate itself, in order
# to ensure the bindings are safe, but until that is done, they are here.
nortcheck = []

test-engine-kv-rocksdb = [
  "engine_test/test-engine-kv-rocksdb"
]
test-engine-raft-raft-engine = [
  "engine_test/test-engine-raft-raft-engine"
]
test-engines-rocksdb = [
  "engine_test/test-engines-rocksdb",
]
test-engines-panic = [
  "engine_test/test-engines-panic",
]

# TODO use encryption/openssl-vendored if later supports
openssl-vendored = [
  "openssl/vendored"
]

[dependencies]
api_version = { workspace = true, default-features = false }
collections = { workspace = true, default-features = false }

derive_more = "0.99.3"
encryption = { workspace = true, default-features = false }
openssl = { workspace = true } # TODO only for feature
engine_rocks = { workspace = true, default-features = false }
engine_traits = { workspace = true, default-features = false }
# TODO: Imported for `test-` features to make cargo clippy happy.
# Need to findout how to fix.
engine_test = { workspace = true, default-features = false }
engine_panic = { workspace = true, default-features = false }
fail = "0.5"
file_system = { workspace = true, default-features = false }
keys = { workspace = true, default-features = false }
kvproto = { workspace = true }
lazy_static = "1.4.0"
libc = "0.2"
log_wrappers = { workspace = true }
num_cpus = "1"
online_config = { workspace = true }
portable-atomic = "0.3"
prometheus = { version = "0.13", features = ["nightly"] }
prometheus-static-metric = "0.5"
protobuf = "2"
proxy_ffi = { workspace = true, default-features = false }
raft = { version = "0.7.0", default-features = false, features = ["protobuf-codec"] }
regex = "1"
serde = "1.0"
serde_derive = "1.0"
slog = { workspace = true }
slog-global = { workspace = true }
slog_derive = "0.2"
tempfile = "3.0"
tikv_alloc = { workspace = true }
tikv_util = { workspace = true, default-features = false }
time = "0.1"

tracker = { workspace = true }
txn_types = { workspace = true, default-features = false }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"
features = ["encryption"]

[dev-dependencies]
rand = "0.8"
toml = "0.5"
