[package]
name = "in_memory_engine"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
testexport = []
failpoints = ["fail/failpoints"]

[[test]]
name = "failpoints"
path = "tests/failpoints/mod.rs"
required-features = ["failpoints"]

[dependencies]
bytes = "1.0"
collections = { workspace = true }
crossbeam = { workspace = true }
crossbeam-skiplist = { workspace = true }
dashmap = "5.1"
engine_rocks = { workspace = true }
engine_traits = { workspace = true }
fail = "0.5"
futures = { version = "0.3", features = ["compat"] }
hex = "0.4"
keys = { workspace = true }
kvproto = { workspace = true }
lazy_static = "1.4.0"
libc = "0.2"
log_wrappers = { workspace = true }
online_config = { workspace = true }
parking_lot = "0.12"
pd_client = { workspace = true }
prometheus = { version = "0.13", default-features = false, features = ["nightly"] }
prometheus-static-metric = "0.5"
raftstore = { workspace = true }
rand = "0.8"
security = { workspace = true }
serde = "1.0"
serde_json = "1.0"
slog = { workspace = true }
slog-global = { workspace = true }
strum = { version = "0.20", features = ["derive"] }
thiserror = "1.0"
tikv_util = { workspace = true }
tokio = { version = "1.5", features = ["rt-multi-thread"] }
txn_types = { workspace = true }
yatp = { workspace = true }

[dev-dependencies]
proptest = "1.0.0"
tempfile = "3.0"
test_pd = { workspace = true }
test_util = { workspace = true }
