[package]
name = "resource_control"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
failpoints = ["fail/failpoints"]

[dependencies]
byteorder = "1.2"
collections = { workspace = true }
crossbeam = "0.8"
crossbeam-skiplist = "0.1"
dashmap = "5.1"
fail = "0.5"
file_system = { workspace = true }
futures = { version = "0.3", features = ["compat"] }
kvproto = { workspace = true }
lazy_static = "1.0"
online_config = { workspace = true }
parking_lot = "0.12"
pd_client = { workspace = true }
pin-project = "1.0"
prometheus = { version = "0.13", features = ["nightly"] }
prost = { workspace = true }
protobuf = { version = "2.8", features = ["bytes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { workspace = true }
slog-global = { workspace = true }
strum = { version = "0.20", features = ["derive"] }
tikv_util = { workspace = true }
tokio-timer = { workspace = true }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dev-dependencies]
rand = "0.8"
test_pd = { workspace = true }
test_pd_client = { workspace = true }
