[package]
name = "security"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
collections = { workspace = true }
encryption = { workspace = true }
kvproto = { workspace = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tikv_util = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
