[package]
name = "security"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
encryption = { path = "../encryption" }
grpcio = { version = "0.7", default-features = false, features = ["openssl-vendored"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tikv_util = { path = "../tikv_util" }
collections = { path = "../collections" }

[dev-dependencies]
tempfile = "3.0"
