[package]
name = "configuration"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "configuration"

[dependencies]
configuration_derive = { path = "./configuration_derive" }
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
toml = "0.4"
