[package]
name = "resource_metering"
version = "0.0.1"
edition = "2018"

[features]
default = ["protobuf-codec"]
failpoints = ["fail/failpoints"]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "grpcio/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "grpcio/prost-codec",
]

[dependencies]
lazy_static = "1.3"
collections = { path = "../collections" }
libc = "0.2"
crossbeam = "0.8"
pin-project = "1.0"
prometheus = { version = "0.12", features = ["nightly"] }
prometheus-static-metric = "0.5"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
tikv_util = { path = "../tikv_util" }
grpcio = { version = "0.9",  default-features = false, features = ["openssl-vendored"] }
online_config = { path = "../online_config" }
serde = "1.0"
serde_derive = "1.0"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
futures = "0.3"
pdqselect = "0.1"
fail = "0.4"
thread-id = "4.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "5125fc1a69496b73b26b3c08b6e8afc3c665a56e" }

[dev-dependencies]
rand = "0.8"

[[test]]
name = "test-recorder"
path = "tests/recorder_test.rs"
required-features = ["failpoints"]
