[package]
name = "resource_metering"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
collections = { workspace = true }
crossbeam = { workspace = true }
futures = "0.3"
grpcio = { workspace = true }
kvproto = { workspace = true }
lazy_static = "1.3"
online_config = { workspace = true }
pdqselect = "0.1"
pin-project = "1.0"
prometheus = { version = "0.13", features = ["nightly"] }
serde = "1.0"
serde_derive = "1.0"
slog = { workspace = true }
slog-global = { workspace = true }
tikv_util = { workspace = true }


[dev-dependencies]
rand = "0.8"

[[test]]
name = "test-recorder"
path = "tests/recorder_test.rs"
