[package]
name = "raftstore-proxy"
version = "0.0.1"
license = "Apache-2.0"
edition = "2018"
publish = false

[lib]
name = "raftstore_proxy"
crate-type = ["cdylib"]

[dependencies]
cmd = { path = "../cmd" }
