[package]
edition = "2018"
name = "concurrency_manager"
publish = false
version = "0.0.1"

[dependencies]
parking_lot = "0.11"
tokio = { version = "0.2", features = ["sync"] }
txn_types = { path = "../txn_types" }
fail = "0.4"

[dependencies.crossbeam-skiplist]
git = "https://github.com/sticnarf/crossbeam.git"
branch = "tikv"
package = "crossbeam-skiplist" 

[dev-dependencies]
rand = "0.7.3"
futures = "0.3"
criterion = "0.3"
tikv_alloc = { path = "../tikv_alloc", features = ["jemalloc"] }

[[bench]]
name = "lock_table"
path = "benches/lock_table.rs"
harness = false
