[package]
edition = "2018"
name = "concurrency_manager"
publish = false
version = "0.0.1"

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "txn_types/protobuf-codec",
]
prost-codec = [
  "txn_types/prost-codec",
]

[dependencies]
parking_lot = "0.11"
tokio = { version = "0.2", features = ["macros", "sync", "time"] }
txn_types = { path = "../txn_types", default-features = false }
fail = "0.4"

[dependencies.crossbeam-skiplist]
git = "https://github.com/crossbeam-rs/crossbeam.git"
tag = "crossbeam-0.7.3"
package = "crossbeam-skiplist" 

[dev-dependencies]
rand = "0.7.3"
futures = "0.3"
criterion = "0.3"
tikv_alloc = { path = "../tikv_alloc", features = ["jemalloc"] }
rayon = "1"

[[bench]]
name = "lock_table"
path = "benches/lock_table.rs"
harness = false
