[package]
name = "encryption_export"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
sm4 = ["encryption/sm4"]

[dependencies]
async-trait = "0.1"
aws = { workspace = true }
azure = { workspace = true }
cloud = { workspace = true }
derive_more = "0.99.3"
encryption = { workspace = true }
error_code = { workspace = true }
file_system = { workspace = true }
gcp = { workspace = true }
kvproto = { workspace = true }
openssl = { workspace = true }
protobuf = { version = "2.8", features = ["bytes"] }
slog = { workspace = true }
# better to not use slog-global, but pass in the logger
slog-global = { workspace = true }
tikv_util = { workspace = true }

[dev-dependencies]
rust-ini = "0.14.0"
structopt = "0.3"
